### ISSUE TITLE
EC2 verification script ignores launch-ec2 errors

### ISSUE THREAD

**Issue by OddBloke** [cloud-init/ubuntu-sru#82]
This is what running the script does (I killed it during the sleep):

```
+ sshopts='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR'
+ for series in $SRU_SERIES
+ echo '### BEGIN xenial'
### BEGIN xenial
++ launch-ec2 --series xenial -u sethostname.yaml
++ awk '/Found/{print $5}'
+ EC2_INST=
+ sleep 60
```

Here is why it should be exiting:

```
$ launch-ec2 --series xenial -u sethostname.yaml
Could not find image-status command. Try git clone https://github.com/smoser/talk-simplestreams.git
$ echo $?
1
```

**Comment by paride** [comment]
The script runs with `set -e`, but the exit status of `launch-ec2` is hidden by the pipe:
```
EC2_INST=`launch-ec2 --series $series -u sethostname.yaml | awk '/Found/{print $5}'`
```
I propose to:
1. make the script use `/bin/bash` instead of `/bin/sh`
2. run the script with `set -o pipefail` (not available in plain sh)
3. check the it still works :)

What do you think?

**Comment by raharper** [comment]
> The script runs with `set -e`, but the exit status of `launch-ec2` is hidden by the pipe:
> 
> ```
> EC2_INST=`launch-ec2 --series $series -u sethostname.yaml | awk '/Found/{print $5}'`
> ```

Since EC2_INST needs to be non-empty, it's sufficient to do this:
```
EC2_INST=`launch_ec2 | awk ... `
[ -z "$EC2_INST" ] && { echo "Failed to launch ec2 instance!"; exit 1; }
```

**Comment by paride** [comment]
Good point Ryan, but it has to be done with the inverse logic, otherwise it will trigger the `set -e`.

**Comment by paride** [comment]
Well, not really, it's one of those `set -e` exceptions!
